version: '3.3'

services:
  db:
    container_name: skeleton-db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  api:
    container_name: skeleton-api
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      - MYSQL_URI=mysql://db:3306

